learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from user_app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^user_app/',include('user_app.urls')),
    url(r'^logout',views.user_logout,name='logout'),
]

learning_users/user_app/urls.py
from django.conf.urls import url
from user_app import views
app_name='user_app'
urlpatterns=[
url(r'^register',views.register,name='register'),
url(r'^user_login',views.user_login,name='user_login'),
]

learning_users/user_app/models.py
from django.db import models
from django.contrib.auth.models import User

class UserInfo(models.Model):
    user=models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)
    portfolio_site=models.URLField(blank=True)


    def __str__(self):
        return self.user.username

learning_users/user_app/forms.py
from django import forms
from django.contrib.auth.models import User
from user_app.models import UserInfo

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=User
        fields=('username','email','password')
class UserInfoForm(forms.ModelForm):
    class Meta():
        model=UserInfo
        fields=('profile_pic','portfolio_site')

learning_users/user_app/views.py
from django.shortcuts import render
from user_app.forms import UserForm,UserInfoForm
from django.contrib.auth import login,logout,authenticate
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
def index(request):
    return render(request,'user_app/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def register(request):
    registered=False
    if request.method=="POST":
        user_form=UserForm(data=request.POST)
        profile_form=UserInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()
            profile=profile_form.save(commit=False)
            profile.user=user
            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']
            profile.save()
            registered=True
        else:
             print(user_form.errors,profile_form.errors)


    else:
        user_form=UserForm()
        profile_form=UserInfoForm()
    return render(request,'user_app/registration.html',{'UserInfo':user_form,'profile_info':profile_form,'registration':registered})



def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not Active")
        else:
            print("Someone with Username:{} and Password:{} tried to login".format(username,password))
            return HttpResponse("Invalid Login Details ")
    else:
        return render(request,'user_app/login.html',{})

learning_users/templates/user_app/base.html
<!DOCTYPE html>
{% load %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- CSS only -->
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light jumbotron" style="background-color: #e3f2fd;">
      <a class="navbar-brand" href="#">Navbar w/ text</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only"></span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user_app:register'%}">Register</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user_app:user_login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
        <span class="navbar-text">
        Welcome to James Website
        </span>
      </div>
    </nav>

<div class="container jumbotron ">
{% block body_block %}
{% endblock %}
</div>
  </body>
</html>

learning_users/templates/user_app/index.html
<!DOCTYPE html>
{% extends "user_app/base.html" %}
{% block body_block %}
<div class="jumbotron">
<h1>Welcome to Django Five</h1>
</div>
{% endblock %}

learning_users/templates/user_app/login.html
{% extends "user_app/base.html" %}
{% block body_block %}
<div class="jumbotron">
  <h1>Please Login</h1>
  <form class="" action="{% url 'user_app:user_login' %}" method="post">
{% csrf_token %}
<label for="username">Username</label>
<input type="text" name="username" placeholder="Enter your Username ">
<label for="password"></label>
<input type="text" name="password" value="">
<input type="submit" name="" value="Login">
  </form>
</div>
{% endblock %}

learning_users/templates/user_app/registration.html
<!DOCTYPE html>
{% extends "user_app/base.html" %}
{% load static %}
{% block body_block %}
<div class="container jumbotron">
  {% if registered %}
  <h1>Thank you for registering</h1>
  {% else %}
  <h1>Register Here</h1>
  <h2>Fill out the form</h2>
  <form class="" enctype="multipart/form-data" method="post">
{% csrf_token %}
{{UserInfo.as_p}}
{{profile_info.as_p}}
{{registration.as_p}}
<input type="Submit" name="" value="Register">
  </form>
  {% endif %}
</div>
{% endblock %}